name: ci
on:
  push:
    branches:
      - master
      - main

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout code
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Thiết lập Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      # 3. Cài đặt MkDocs và các plugin cần thiết
      - name: Install dependencies
        run: |
          pip install mkdocs-material
          pip install mkdocs-roamlinks-plugin
          pip install mkdocs-rss-plugin
          # pip install mkdocs-mermaid2-plugin  # nếu cần

      # 4. Build MkDocs site
      - name: Build MkDocs site
        run: mkdocs build

      # 5. Deploy lên AWS S3
      - name: Sync to S3
        uses: jakejarvis/s3-sync-action@v0.5.1
        with:
          args: --acl public-read --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ap-southeast-1          # Đặt theo region bucket của bạn
          SOURCE_DIR: ./site